### ISSUE TITLE
PersistLoadingAction missing in 0.8

### ISSUE THREAD

**Issue by zaubererty** [Cretezy/redux_persist#41]
What is the concept of replacing this action.
I have issues without being notified when a load happens.

Please advice.

Btw I miss a breaking change notice.

**Comment by Cretezy** [comment]
The [CHANGELOG](https://github.com/Cretezy/redux_persist/blob/master/packages/redux_persist/CHANGELOG.md#080-rc0---2018-11-06) states that they were removed and are a breaking change (as expected by the major version bump, minor for <1.0.0).

Basically, you should call `.load()` manually instead of relying on actions. This makes loading much simpler, as it's always called before the application load. See the README for an example.

Is there any use case that isn't covered by this?

**Comment by zaubererty** [comment]
I did some additional loading when the app state has been loaded. 

The other use case where to get notified when loading is complete to do additional work.

Off cause you can do the loading and all the other stuff by your self but then I might switch better to the BloC pattern and do everything myself.

Oh now I see "Breaking: Change saving/loading" means removed actions, sorry my mistage.

**Comment by Cretezy** [comment]
You can easily do this current. Simply dispatch your own action after loading.

```dart
persistor.load().then(() => store.dispatch(LoadedAction()));
```
