### ISSUE TITLE
Ability to Programmatically Delete Persisted Data

### ISSUE THREAD

**Issue by tuckerjt07** [Cretezy/redux_persist#54]
Is there the ability to delete persisted data from the store during development?

**Comment by Cretezy** [comment]
What do you mean delete? Like delete the persisted file or data inside your state?

**Comment by tuckerjt07** [comment]
Delete the persisted file so that state can be blanked and load from an empty state when testing. I know I can change the key and it will do the same but would like to be able to do it without continually incrementing that name.

**Comment by Cretezy** [comment]
You can also just not load the state, which would be as if you are using a new file:

```dart
final loadedState = persistor.load();
// to
final loadedState = null; // persistor.load();
```

**Comment by Cretezy** [comment]
To reset, you can call `.save(null)` on your storage to write an empty file BTW, just leaving this here for reference.

**Comment by connlaoi** [comment]
Leaving this comment for additional clarity.

In my case, I was calling my sign-out action inside middleware after clearing image caches, local storage, and shared preferences. As you would if you were using it to signal a successful middleware http response. However, doing this at the end of the "sign-out purge" caused the persistor to ignore the AppState.initial() which was being called by my sign-out action. Likely due to thunk middleware processing.

Solution: I moved the store.dispatch(Actions.SignoutSuccess) call to the very start of the sign-out thunk middleware function. Then after purging, I call *.save(null) on my storage provider just before redirecting to the onboarding screen in order to trigger the built in AppState.initial() overwrite.
